import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/jumiTest.module.css";
import NavBar from "@/components/NavBar";
import Buttons from "@/components/Buttons"

export default function jumiTest() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Buttons/>
        <NavBar/>
        
      </main>
    </>
  );
}