import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/PromptPage.module.css"
import PromptDesc from "@/components/PromptDesc";
import ChipsX from "@/components/ChipsX";


export default function Home() {
  return (
    <>
      <Head>
        <title>Prompt Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div>
          <ChipsX />
        </div>
        <div>
          <p>"</p>
          <p>A chase with a happy dog, a wagging tail, and an adventurous pursuit </p>
          <p>"</p>
        </div>
        <div>
          <PromptDesc/>
        </div>
      </main>
    </>
  );
}
