import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/PromptPage.module.css"
import PromptDesc from "@/components/PromptDesc";
import ChipsX from "@/components/ChipsX";
import NavBar from "@/components/NavBar";
import { useState,useEffect } from "react";
import Link from "next/link";


export default function Home() {

  const [drawingPrompt, setDrawingPrompt] = useState([]);
  useEffect(() => {
    console.log(localStorage.getItem('Prompt'));
    const prompt = localStorage.getItem('Prompt').trim().split('%');
    console.log(prompt);
    setDrawingPrompt(prompt);
  }, [])
  return (
    <>
      <Head>
        <title>Prompt Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.header}>
          <ChipsX />
        </div>
        <div className={styles.promptCard}>
          <p className={styles.quotation1}>“</p>
          <p className={styles.prompt}>{drawingPrompt[1]}</p>
          <p className={styles.quotation2}>”</p>
        </div>
        <div>
          <PromptDesc title={drawingPrompt[0]} description={drawingPrompt[2]}/>
        </div>
        <div className={styles.regenerateButtonContainer}>
          <Link href="/NewPrompt">
            <button className={styles.regenerateButton}>Regenerate</button>
          </Link>
        </div>
        <div className={styles.footer}>
          <NavBar/>
        </div>
      </main>
    </>
  );
}
